/// Flutter icons MorpheusIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MorpheusIcons
///      fonts:
///       - asset: fonts/MorpheusIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class MorpheusIcons {
  MorpheusIcons._();

  static const _kFontFam = 'MorpheusIcons';
  static const String? _kFontPkg = null;

  static const IconData patreon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kofi = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vanilla = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modded = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_mark = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket = IconData(0xf135, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
